version: '3'

services:
  planet-service:
    build: ./planet-service
    ports:
      - "8000:8000"
    networks:
      - insecure-microservices
    environment:
      - JWT_SIGNING_KEY=your-signing-key-here
      - JWT_ENCRYPTION_KEY=your-encryption-key-here
      - ADMIN_API_KEY=your-admin-key-here

  destruction-service:
    build: ./destruction-service
    ports:
      - "8001:8001"
    networks:
      - insecure-microservices
    environment:
      - JWT_SIGNING_KEY=your-signing-key-here
      - JWT_ENCRYPTION_KEY=your-encryption-key-here
      - ADMIN_API_KEY=your-admin-key-here

  creation-service:
    build: ./creation-service
    ports:
      - "8002:8002"
    networks:
      - insecure-microservices
    environment:
      - JWT_SIGNING_KEY=your-signing-key-here
      - JWT_ENCRYPTION_KEY=your-encryption-key-here
      - ADMIN_API_KEY=your-admin-key-here

  auth-service:
    build: ./auth-service
    ports:
      - "8003:8003"
    networks:
      - insecure-microservices
    environment:
      - JWT_SIGNING_KEY=your-signing-key-here
      - JWT_ENCRYPTION_KEY=your-encryption-key-here
      - ADMIN_API_KEY=your-admin-key-here

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - insecure-microservices
    depends_on:
      - planet-service
      - destruction-service
      - creation-service
      - auth-service

networks:
  insecure-microservices:
    driver: bridge 